### ISSUE TITLE
Rename example/.env.example to example/.env.local

### ISSUE THREAD

**Issue by thibault-tiro** [zedwerks/keycloak-smart-fhir#6]
Hi,

Thanks for making this library open source. It looks really promising.

RIght now, the quickstart.sh does not work out of the box. It has a reference to example/.env.local which does not exist (similar for the deploy and configure scripts).

I would rename example/.env.example to example/.env.local or update the scripts.

Best,
Thibault

**Comment by bradhead** [comment]
This is now fixed. The idea was to name the env.local yourself and set any secrets you have there.. but now I have checked for absence of .env.local and then try to use the .env.example that is included. This gets the system up and running in your Docker desktop without mods.

**Comment by bradhead** [comment]
BTW,  I am going to be adding standalone launch. The recent edition puts the EHR-launch context endpoint as an endpoint native to Keycloak. This means you don't need a separate context service running...
